AWSTemplateFormatVersion: 2010-09-09
Description: Simple S3 Template
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "lokiis-simple-s3-bucket-20250903"
      AccessControl: Private
      VersioningConfiguration:
        Status: "Enabled"